name: Deploy to cPanel

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-
    
    strategy:
    matrix:
    node-version: [14.x, 16.x, 18.x, 20.x]


    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm  insatll

      - name: Build React App
        run: npm  run build
        

      - name:  Uplaod to cPanel📂 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          exclude: |
            **/.git**
            **/.git*/**
            **/node_modules/**
            **/.**




          